<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Olivier Maurel Website</title>
    <link rel="stylesheet" href="styles/style.css"/>
    <link rel="stylesheet" href="styles/normalize-3.0.3.min.css"/>
</head>
<body onkeydown="keyPress(event.key)">
    <div id="pattern" class="pattern">
        <div class="top-block block"></div>
        <div class="left-block block"></div>
        <div class="center-block block">
            <h1>Olivier Maurel</h1>
        </div>
        <div class="right-block block"></div>
        <div class="bottom-block block"></div>
    </div>
    <script src="scripts/main.js"></script>
</body>
</html>